[project]
name = "merge-ics"
version = "0.1.0"
description = "Merge ICS calendar files"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.14,<3.15"
dependencies = [
    "icalendar>=6.3.2",
    "typer>=0.20.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]

[tool.ruff]
line-length = 120
